{% set name = "hydrosignatures" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydrosignatures-{{ version }}.tar.gz
  sha256: 8f6ebdca539192819e076ec4877487d45bbbcb06402513fc35bddbdb5c1b9e6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - scipy

test:
  imports:
    - hydrosignatures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/hydrosignatures
  summary: A collection of tools for computing hydrological signatures
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hyriver.io/

extra:
  recipe-maintainers:
    - cheginit
