{% set name = "hydrosignatures" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fd6414085ba61088fcda80c3ed061551e0edb691e044a651fe4148b8fc3d2f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - pandas >=1.0
    - scipy
    - xarray >=2023.03.0

test:
  imports:
    - hydrosignatures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/hydrosignatures
  summary: A collection of tools for computing hydrological signatures
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hyriver.io/

extra:
  recipe-maintainers:
    - cheginit
